// tui/src/components/nag/UpgradeNag.tsx
// Copyright (c) 2026 whizBANG Developers LLC. All rights reserved.
// Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE.
import React from 'react'
import { Box, Text, useInput } from 'ink'
import { TIERS, TIER_LABELS } from '../../constants/vocabularies.js'

interface UpgradeNagProps {
  featureName: string
  featureDescription?: string
  requiredTier: typeof TIERS.SOLO | typeof TIERS.FABRICK
  features?: string[]
  onBack: () => void
}

export function UpgradeNag({ featureName, featureDescription, requiredTier, features, onBack }: UpgradeNagProps) {
  useInput((input, key) => {
    if (key.escape || key.return || input === 'b') onBack()
  })

  const tierColor = requiredTier === TIERS.FABRICK ? 'magenta' : 'yellow'
  const tierLabel = TIER_LABELS[requiredTier] ?? 'Weaver'

  return (
    <Box flexDirection="column" paddingX={2} paddingY={1}>
      <Text bold color={tierColor}>Upgrade to {tierLabel}</Text>

      <Box marginTop={1} flexDirection="column">
        <Text bold>{featureName}</Text>
        <Text dimColor>
          {featureDescription || `This feature requires a ${tierLabel} license.`}
        </Text>
      </Box>

      {features && features.length > 0 && (
        <Box marginTop={1} flexDirection="column">
          {features.map(f => (
            <Text key={f}>  <Text color="green">+</Text> {f}</Text>
          ))}
        </Box>
      )}

      <Box marginTop={1}>
        <Text dimColor>Learn more: https://weaver-dev.github.io/pricing</Text>
      </Box>

      <Box marginTop={1}>
        <Text dimColor>Press Esc, b, or Enter to go back</Text>
      </Box>
    </Box>
  )
}

// code/src/components/nag/UpgradeNag.vue
<!-- Copyright (c) 2026 whizBANG Developers LLC. All rights reserved. -->
<!-- Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE. -->
<template>
  <q-card v-if="!publicDemo" flat bordered class="upgrade-nag q-pa-md">
    <q-card-section class="text-center q-pa-lg">
      <q-icon :name="tierIcon" size="48px" :color="tierColor" />
      <div class="text-h6 q-mt-md">{{ featureName }}</div>
      <div class="text-body2 text-grey-7 q-mt-sm">
        {{ featureDescription || defaultDescription }}
      </div>
      <div v-if="features && features.length" class="q-mt-md text-left" style="display: inline-block">
        <div v-for="f in features" :key="f" class="text-body2 q-mb-xs">
          <q-icon name="mdi-check" color="positive" size="xs" class="q-mr-xs" />
          {{ f }}
        </div>
      </div>
      <div class="q-mt-lg">
        <q-btn
          :color="tierColor"
          :label="ctaLabel"
          no-caps
          unelevated
          :href="ctaHref"
          target="_blank"
        />
      </div>
    </q-card-section>
  </q-card>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { isPublicDemo } from 'src/config/demo'
import { TIERS, type TierName } from 'src/constants/vocabularies'

const props = withDefaults(defineProps<{
  featureName: string
  featureDescription?: string
  requiredTier?: TierName
  features?: string[]
}>(), {
  requiredTier: TIERS.WEAVER,
})

const publicDemo = isPublicDemo()

const tierIcon = computed(() =>
  publicDemo
    ? (props.requiredTier === TIERS.FABRICK ? 'mdi-domain' : 'mdi-clock-outline')
    : (props.requiredTier === TIERS.FABRICK ? 'mdi-domain' : 'mdi-star'),
)

const tierColor = computed(() =>
  props.requiredTier === TIERS.FABRICK ? 'deep-purple' : 'amber-8',
)

const defaultDescription = computed(() => {
  if (publicDemo) {
    return props.requiredTier === TIERS.FABRICK
      ? `${props.featureName} is coming in the FabricK edition.`
      : `${props.featureName} is coming soon in the Weaver edition.`
  }
  return `This feature requires a ${props.requiredTier} license.`
})

const ctaHref = computed(() =>
  publicDemo
    ? 'https://github.com/whizbangdevelopers-org/Weaver-Free/discussions'
    : 'https://weaver-demo.github.io/pricing',
)

const ctaLabel = computed(() => {
  if (publicDemo) {
    return props.requiredTier === TIERS.FABRICK ? 'Request Early Access' : 'Join the Beta'
  }
  return props.requiredTier === TIERS.FABRICK ? 'Upgrade to FabricK' : 'Upgrade to Weaver'
})
</script>
