// tui/src/components/DemoBanner.tsx
// Copyright (c) 2026 whizBANG Developers LLC. All rights reserved.
// Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE.
import React from 'react'
import { Box, Text } from 'ink'
import { DEMO_VERSIONS, tierDisplayLabel, type DemoVersionEntry } from '../demo/mock.js'

interface DemoBannerProps {
  tier: string
  version: string
}

export function DemoBanner({ tier, version }: DemoBannerProps) {
  const vInfo: DemoVersionEntry | undefined = DEMO_VERSIONS.find(v => v.version === version)
  const label = tierDisplayLabel(tier)
  return (
    <Box paddingX={1} flexDirection="column">
      <Box>
        <Text backgroundColor="yellow" color="black" bold>
          {' DEMO MODE '}
        </Text>
        <Text color="cyan" bold> {label} </Text>
        <Text dimColor>| </Text>
        <Text color="magenta" bold>v{version}</Text>
        <Text dimColor> {vInfo?.headline ?? ''} </Text>
        <Text dimColor>| </Text>
        <Text dimColor>[Tab] tier  [←/→] version</Text>
      </Box>
    </Box>
  )
}

// src/components/DemoBanner.vue
<!-- Copyright (c) 2026 whizBANG Developers LLC. All rights reserved. -->
<!-- Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE. -->
<template>
  <div v-if="isDemo" class="demo-banner row items-center no-wrap q-px-md">
    <span class="text-white text-weight-bold">Demo Mode</span>
    <span v-show="isPublic" class="text-white q-mx-sm">|</span>
    <a
      v-show="isPublic"
      :href="PUBLIC_DEMO_LINKS.fmProgram"
      target="_blank"
      rel="noopener noreferrer"
      class="text-white text-weight-bold demo-banner__link"
    >
      Become a Founding Member
    </a>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { isDemoMode as checkDemoMode, isPublicDemo, PUBLIC_DEMO_LINKS } from 'src/config/demo-mode'

const isDemo = computed(() => checkDemoMode())
const isPublic = computed(() => isPublicDemo())
</script>

<style scoped lang="scss">
.demo-banner {
  background-color: #f59e0b;
  font-size: 0.875rem;
  white-space: nowrap;
}

.demo-banner__link {
  text-decoration: underline;
  transition: opacity 0.2s ease;

  &:hover {
    opacity: 0.85;
  }
}
</style>
